[package]
name = "markdown-html"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
pulldown-cmark = "0.12"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
